# Generated by Django 5.1.7 on 2025-03-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiles',
            options={'ordering': ('name',), 'verbose_name_plural': 'profiles'},
        ),
        migrations.AddField(
            model_name='profiles',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='firstname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_image'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='work',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
